[unstable]
build-std = ["core", "compiler_builtins"]

[build]
target = "i386-rust_dos.json"
rustflags = [
    "-C",
    "link-arg=-Tlink.x", 
    "-Zlocation-detail=none", 
    # "-Zfmt-debug=none"
]
